### ISSUE TITLE
Android clients

### ISSUE THREAD

**Issue by vstavrinov** [morrownr/8821cu-20210916#102]
I am using it as an access point in the Linux box to serve Android clients. Android 13 works well, but Android 5 and 9 doesn't. They both see the AP but couldn't connect. Android 9 says "couldn't find", and Android 5 says nothing. There are no any of their footprints in AP logs. So I have no points to where to seek the reason.

**Comment by morrownr** [comment]
Hi @vstavrinov 

My first guess would have to do with security. Is your access point set to use WPA2, mixed, WPA3 or something else?

Those older versions of Android likely will not support anything later than WPA2 so anything later than that in your AP will get you what you are seeing.

**Comment by vstavrinov** [comment]
WP2 used in all cases, so it doesn't matter. This problem appears with NetworkManager and not with hostapd so it is not related to the driver. Sorry.
