### ISSUE TITLE
[Compilation] Success for Libreelec/Raspberry Pi kernel 6.1.38

### ISSUE THREAD

**Issue by smirko** [morrownr/8821cu-20210916#104]
Hi,
I don't have other means of contacting you, so I'm writing here.
Since you have a list of supported kernels / platforms, you can add RPi 6.1.38 to the list.
Thanks!

**Comment by smirko** [comment]
Also, feel free to close the issue once you read this ;)

**Comment by morrownr** [comment]
Thanks for letting me know. I've updated my working repo and will get it into the repo soon.
