### ISSUE TITLE
Install fails on Raspberry Pi OS with kernel 6.1.42-v8+ (aarch64)

### ISSUE THREAD

**Issue by mirek-burkon** [morrownr/8821cu-20210916#110]
Hi, can you please advise me on this?

sudo ./install-driver.sh
: ---------------------------
: install-driver.sh v20230227
: aarch64 (architecture)
: 4/4 (in-use/total processing units)
: 3884804 (total system memory)
: 6.1.42-v8+ (kernel version)
: gcc (Debian 10.2.1-6) 10.2.1 20210110
: dkms:2.8
: ---------------------------

Checking for previously installed drivers.
rtl8821cu, 5.12.0.4: added
rtl8821CU, 5.4.1, 5.10.0-24-arm64, aarch64: installed
: ---------------------------

Removing a dkms installation.

------------------------------
Deleting module version: 5.12.0.4
completely from the DKMS tree.
------------------------------
Done.
Removing 8821cu.conf from /etc/modprobe.d
Removing source files from /usr/src/rtl8821cu-5.12.0.4
Removal complete.
: ---------------------------

Starting installation.
Installing 8821cu.conf to /etc/modprobe.d
The dkms installation routines are in use.
Copying source files to /usr/src/rtl8821cu-5.12.0.4

Creating symlink /var/lib/dkms/rtl8821cu/5.12.0.4/source ->
                 /usr/src/rtl8821cu-5.12.0.4

DKMS: add completed.
The driver was added to dkms successfully.
: ---------------------------

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
./dkms-make.sh..........................................................................(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.42-v8+ (aarch64)
Consult /var/lib/dkms/rtl8821cu/5.12.0.4/build/make.log for more information.
An error occurred. dkms build error:  10
Please report this error.
Please copy all screen output and paste it into the problem report.
Run the following before reattempting installation.
$ sudo ./remove-driver.sh

cat /var/lib/dkms/rtl8821cu/5.12.0.4/build/make.log
DKMS make.log for rtl8821cu-5.12.0.4 for kernel 6.1.42-v8+ (aarch64)
Mon 14 Aug 2023 05:38:10 PM PDT
make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/6.1.42-v8+/build M=/var/lib/dkms/rtl8821cu/5.12.0.4/build  modules
make[1]: Entering directory '/home/killbot/linux-431319d91b8584c9f28b195ab9a97d7e78905aeb'
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_chplan.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/monitor/rtw_radiotap.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/wds/rtw_wds.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_ft.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_wnm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_mbo.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_rm_util.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_roch.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/aes-internal.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/aes-internal-enc.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/aes-gcm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/aes-ccm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/aes-omac1.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/ccmp.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/gcmp.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/aes-siv.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/aes-ctr.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/sha256-internal.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/sha256.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/sha256-prf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/crypto/rtw_crypto_wrap.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/core/rtw_swcrypto.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/wifi_regd.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/rtw_android.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/rtw_proc.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/nlrtw.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/os_dep/linux/rtw_rhashtable.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_intf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_com.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_com_phycfg.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_phy.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_dm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_dm_acs.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_btcoex.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_mp.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_mcc.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_hci/hal_usb.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/led/hal_led.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/led/hal_usb_led.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/rtl8821c_halinit.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/rtl8821c_mac.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/rtl8821c_cmd.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/rtl8821c_phy.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/rtl8821c_dm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/rtl8821c_ops.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/hal8821c_fw.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/usb/rtl8821cu_halinit.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/usb/rtl8821cu_halmac.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/usb/rtl8821cu_io.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/usb/rtl8821cu_xmit.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/usb/rtl8821cu_recv.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/usb/rtl8821cu_led.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/rtl8821c/usb/rtl8821cu_ops.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/efuse/rtl8821c/HalEfuseMask8821C_USB.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/hal_halmac.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_api.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_dbg.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_bb_rf_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_cfg_wmac_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_common_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_efuse_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_flash_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_fw_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_gpio_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_init_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_mimo_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_usb_88xx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_8821c/halmac_cfg_wmac_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_8821c/halmac_common_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_8821c/halmac_gpio_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_8821c/halmac_init_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_8821c/halmac_phy_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_8821c/halmac_pwr_seq_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/halmac/halmac_88xx/halmac_8821c/halmac_usb_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_debug.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_antdiv.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_soml.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_smt_ant.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_antdect.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_interface.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_phystatus.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_hwconfig.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_dig.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_pathdiv.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_rainfo.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_dynamictxpower.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_adaptivity.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_cfotracking.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_noisemonitor.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_beamforming.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_direct_bf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_dfs.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/txbf/halcomtxbf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/txbf/haltxbfinterface.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/txbf/phydm_hal_txbf_api.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_adc_sampling.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_ccx.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_psd.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_primary_cca.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_cck_pd.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_rssi_monitor.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_auto_dbg.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_math_lib.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_api.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_pow_train.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_lna_sat.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_pmac_tx_setting.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_mp.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/phydm_cck_rx_pathdiv.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/halrf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/halrf_debug.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/halphyrf_ce.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/halrf_powertracking_ce.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/halrf_powertracking.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/halrf_kfree.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/halrf_psd.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/rtl8821c/halhwimg8821c_bb.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/rtl8821c/halhwimg8821c_mac.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/rtl8821c/phydm_hal_api8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/rtl8821c/phydm_regconfig8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/rtl8821c/phydm_rtl8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/rtl8821c/halhwimg8821c_rf.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/rtl8821c/halrf_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/phydm/halrf/rtl8821c/halrf_iqk_8821c.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/btc/halbtc8821cwifionly.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/btc/halbtc8821c1ant.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/hal/btc/halbtc8821c2ant.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/platform/platform_ops.o
  LD [M]  /var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.o
  MODPOST /var/lib/dkms/rtl8821cu/5.12.0.4/build/Module.symvers
ERROR: modpost: "__arch_copy_to_user" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "preempt_schedule_notrace" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "alt_cb_patch_nops" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "__udelay" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "csum_ipv6_magic" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "__rcu_read_unlock" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "__rcu_read_lock" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "_raw_spin_unlock" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "__arch_copy_from_user" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
ERROR: modpost: "__const_udelay" [/var/lib/dkms/rtl8821cu/5.12.0.4/build/8821cu.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:126: /var/lib/dkms/rtl8821cu/5.12.0.4/build/Module.symvers] Error 1
make[1]: *** [Makefile:1964: modpost] Error 2
make[1]: Leaving directory '/home/killbot/linux-431319d91b8584c9f28b195ab9a97d7e78905aeb'
make: *** [Makefile:2501: modules] Error 2

**Comment by morrownr** [comment]
Hi @mirek-burkon 

That is a little mess you have there.

The devs of the Raspberry Pi OS are notorious for screwing up the header files and this very well could be one of those cases. However. In looking at the age of the distro as it originally was installed and the much more modern kernel, it may be hard for us to sort this out. It may be easier to backup the important files and do a clean installation with a current version of RasPiOS.

With that said, If your Pi is a Pi4B/400/CM4, be careful about installing the 32 bit version as they have a trap for you so I recommend the 64 bit version.

**Comment by mirek-burkon** [comment]
Thanks @morrownr, seems like I messed up the image myself, possibly by apt full-upgrade. Yes, it's Pi 4B and the newer kernel seems necessary to get the VideoCore VI chipset working. I rolled back to the original Pi OS with 6.1.21-v8+ kernel and compiled 8821cu just fine following your description. Appreciate the help!

**Comment by morrownr** [comment]
Glad you are working again. I understand the desire to get that newer drivers working but adding a bleeding edge kernel sometimes can make a mess.

Cheers
