### ISSUE TITLE
Works on kernel 6.4 on Ubuntu

### ISSUE THREAD

**Issue by raicabogdan** [morrownr/8821cu-20210916#113]
Confirmed to work on 6.4.11-060411-generic

`
===============================================================================
                       Device details (wlx90916400e0c7)
===============================================================================
GENERAL.DEVICE:                         wlx90916400e0c7
GENERAL.TYPE:                           wifi
GENERAL.NM-TYPE:                        NMDeviceWifi
GENERAL.DBUS-PATH:                      /org/freedesktop/NetworkManager/Devices/3
GENERAL.VENDOR:                         Realtek Semiconductor Corp.
GENERAL.PRODUCT:                        802.11ac NIC
GENERAL.DRIVER:                         rtl8821cu
GENERAL.DRIVER-VERSION:                 v5.12.0.4-1-g9241a6516.20210916
GENERAL.FIRMWARE-VERSION:               24.8
GENERAL.HWADDR:                         90:91:64:00:E0:C7
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.REASON:                         0 (No reason given)
GENERAL.IP4-CONNECTIVITY:               4 (full)
GENERAL.IP6-CONNECTIVITY:               3 (limited)
GENERAL.UDI:                            /sys/devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.2/net/wlx90916400e0c7
GENERAL.PATH:                           pci-0000:00:14.0-usb-0:12:1.2
GENERAL.IP-IFACE:                       wlx90916400e0c7
GENERAL.IS-SOFTWARE:                    no
GENERAL.NM-MANAGED:                     yes
GENERAL.AUTOCONNECT:                    yes
GENERAL.FIRMWARE-MISSING:               no
GENERAL.NM-PLUGIN-MISSING:              no
GENERAL.PHYS-PORT-ID:                   --
GENERAL.CONNECTION:                     DEFAULT CONNECTION
GENERAL.CON-UUID:                       15e17caa-64e0-43e5-b509-8c7c57232277
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/5
GENERAL.METERED:                        no (guessed)

`

**Comment by morrownr** [comment]
Thanks @raicabogdan 

FYI: Kernel 6.4 has an in-kernel driver for this chipset. Installing this driver with install-driver.sh will blacklist the in-kernel driver and remove-driver.sh will remove the blacklist. If you install manually, you will have to set up your own blacklist.

For most information, research rtw88.

Regards

**Comment by raicabogdan** [comment]
Thank you as well, unfortunately the built-in one was not working. I tried using that one first, was detecting the network, but was not able to connect to it. Was a strange issue.

**Comment by morrownr** [comment]
I've been testing the in-kernel 8812bu driver and it is working well here. I guess I need to test the in-kernel driver for this chipset.

What is the vid/pid for your adapter?

$ lsusb

**Comment by raicabogdan** [comment]
Sure thing, here is the full output of the lsusb for the wifi dongle.

`Bus 001 Device 006: ID 0bda:c820 Realtek Semiconductor Corp. 802.11ac NIC`

**Comment by morrownr** [comment]
I've confirmed that the 8821cu rtw88 driver is not working. I tested kernels 6.2 - 6.5. It may be that Sasha does not have a 8811cu adapter to test. I will contact him and see what he wants us to do as far as when he can work on it and what he needs from us testers. Are you available to help?

@raicabogdan

**Comment by morrownr** [comment]
I emailed the developer and maintainer of the usb support for rtw88. I explained the situation and offered help to get it fixed. I hope to hear something back soon.

**Comment by raicabogdan** [comment]
Sure, my work PC is on kernel 6 so I could just uninstall the github driver and test it. If I recall right, the uninstallation reverts back to the built-in driver, no ?

**Comment by morrownr** [comment]
> If I recall right, the uninstallation reverts back to the built-in driver, no ?

If you are using the driver in this repo and you use the below to remove the driver:

sudo sh remove-driver.sh

The in-kernel driver was included starting with kernel 6.2 so anything older won't work.

There is no need to do anything right now as I have confirmed the in-kernel 8821cu driver is dead.

I'll let you know.
