### ISSUE TITLE
Suggest this driver into Linux Kernel mailing list

### ISSUE THREAD

**Issue by konung-yaropolk** [morrownr/8821cu-20210916#119]
Default In-kernel driver rtw88 is awful and completely unstable.
As this one driver is licensed under GPL-2, theoretically it can be merged into mainline kernel and first step to do it - send suggestion into kernel mailing list. 
Is this possible to do, or given code is not compatible to be merged into kernel?

Thanks

**Comment by morrownr** [comment]
> Is this possible to do, or given code is not compatible to be merged into kernel?

Can't do it. This driver does not meet Linux Wireless Standards and would be refused.This is all on Realtek. They have know for a long long time and have done nothing. The in-kernel usb driver support is by a community member, not Realtek. FWIW: the mt8812bu support in the rtw88 driver is pretty good.

On the other hand, Mediatek fully supports all of their modern chipsets with very good drivers and the effort is led by Mediatek employees with a few patches at times from the community. The site Main Menu:

https://github.com/morrownr
