### ISSUE TITLE
not working on 6.6.5-arch1-1

### ISSUE THREAD

**Issue by erroor234** [morrownr/8821cu-20210916#133]
i cannot access shell for some reason (i dont know even why) so i managed to copy journalctl log 
[text1.txt](https://github.com/morrownr/8821cu-20210916/files/13647517/text1.txt) <- this is log file 
i am using official arch linux and its kernel. Also dont work on lts arch kernel (and CachyOS kernels and Zen kernel too)
I also tried rtl8821cu-morrownr-dkms-git, but it not working 
Also doesnt work in arch live iso

**Comment by erroor234** [comment]
i forgot 
Secure Boot disabled

**Comment by erroor234** [comment]
secure boot disabled

**Comment by morrownr** [comment]
Hi @erroor234 

The problem is a Mainline kernel bug. Back up to the last known good kernel and then use it until Arch issues a new kernel.

**Comment by erroor234** [comment]
I am using lastest kernel from core-testing and it is working. Also checked on linux-zen and linux-lts from core-testing 
but I did the following:
Disabled NetworkManager (`sudo systemctl disable NetworkManager`) 
Rebooted 
Enabled NetworkManager (`sudo systemctl enable NetworkManager`)
Rebooted 
Not it works

**Comment by morrownr** [comment]
Copy all. Any releases based on mainline 6.6.6 or later should be good.
