### ISSUE TITLE
Good work but not yet there.

### ISSUE THREAD

**Issue by moonlightz** [morrownr/8821cu-20210916#135]
Hi. Glad someone is trying to sort this mess out.
This week, I bought online an Mercusys MUH6, it came yesterday (Dec 14th). I opened the box, nice looking device, yada yada. When I inserted the dongle to one of the USB ports of a TV Box that is running Linux over mSD (Armbian) and entered lsusb.... I got puzzled... I saw 8188GU 802.11n. I looked better to the box and indeed, it says dual band. The lsusb said CD-rom mode, so I searched the interwebs and found out that I would need to install usb-modeswitch and use the command kw -v something -p something and it switched the device from cdrom mode to 802.11ac NIC and now it says 8821cu instead of 8188gu. I never seen a thing like this.
After that, the device is being using 8821cu linux's built-in driver. But I stumbled upon another block... it doesn't like airmon-ng. Someone recommends using iw ..... monitor none command, which indeed enables monitor mode but when I see sudo iwconfig, I see 802.11b and some other weird things.
Then another searching lead me here. I cloned the repo, I ran the sudo ./install....sh, all fine, no problems, I didn't change a thing, it asked to reboot.... and it seems the device is using the driver. I can see the networks as ususal. I ran sudo airmon-ng start wlan1. It enabled the monitor mode, I ran wash -i wlan1, I see networks where I wasn't able to see them. BUT when I let it run for some time, it seems to repeat once or twice a network (I'm at fault here probably because reaver is compiled from source to allow -M). 
Then I stop wash -i wlan1 and run it again... and it is not working as usual. It's not showing networks or it just showing one or two, or three. Same if I use wash -i wlan1 -5.
I didn't not try debian x64 yet on a laptop.
I guess... the so-called embedded wireless chips do suck for monitor mode. Mercusys (a make I never heard of) put an nice antenna but the chip and it's oriented Windows' ROM do suck. I wonder why companies are picking the leftovers of chips that way outdated...
I'm not expecting to see this problem fixed. I will try with debian x64 tomorrow... unfortunatelly I deleted the VM... days ago.

**Comment by morrownr** [comment]
@moonlightz 

Oh my. I need to you to take couple of deep breathes and have a good chat with me. 

If you are looking to do monitor mode work such as security analysis or pen testing, your best option is to send this rtl8821cu based adapter back and get your money back. If you keep it, you are looking at a lot of frustration.

I'd suggest that you go to the site Main Menu and post something in Issues that goes something like this:

Subj: Need help picking out a usb wifi adapter

I will be using the adapter to do monitor mode work such security analysis or pen testing. I need active monitor mode. frame injection, deauth and package capture capability. Add or change whatever you want.

---

Hint: your best chipsets will be mt7921au, mt7612u and mt7610u. The mt7921u driver currently has a bug in active monitor mode but we are working with the devs to get it fixed. Regular monitor mode is fine. Active monitor mode in the other 2 chips works well. All 3 chips are fully Linux Wireless Standards compliant. I can even suggest some adapters from the Plug and Play list.

There are some pretty smart monitor mode users that stop by the Main Menu to see what is up. Remember that the Main Menu is located:

https://github.com/morrownr/USB-WiFi
