### ISSUE TITLE
More recent Realtek oot drive source available in Nvidia repo

### ISSUE THREAD

**Issue by hjmallon** [morrownr/8821cu-20210916#154]
I have just found a March 2024 version of the Realtek shared parts of the WiFi driver here in Nvidia's operating system for their Jetson hardware. Might be useful as a reference?

```
#define DRIVERVERSION   "v5.14.0.4-217-g7a0377e61.20240410_COEX20240327-2727_beta"
#define BTCOEXVERSION   "COEX20240327-2727"
```

https://nv-tegra.nvidia.com/r/gitweb?p=linux-nv-oot.git;a=blob;f=drivers/net/wireless/realtek/rtl8822ce/include/rtw_version.h;h=9b7b9a8b1f76c28c6bd237cc849a88a428b03158;hb=refs/heads/rel-36

**Comment by morrownr** [comment]
@hjmallon 

Thanks for the information, however, I actually have the release version of that update:

#define DRIVERVERSION	"v5.15.9.4-5-gee5c3ac0b.20240429_COEX20230331-5d5d"
#define BTCOEXVERSION	"COEX20230331-5d5d"

I've been slowly taking a look at it. It can take a while to go from fresh source to a repo that I will take public.

I am very busy right now helping get new drivers and fixes ready to go upstream into the kernel. That includes patches to rtw88_8821cu which should support the same chips as the driver in this repo.

Would you be interested in testing the rtw88 downstream repo to give us feedback?
