### ISSUE TITLE
Serious packet loss

### ISSUE THREAD

**Issue by miny1233** [morrownr/8821cu-20210916#69]
root@miny1233-EZpad:~# ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=2.59 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=45.7 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=2.87 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=64 time=2.81 ms
64 bytes from 192.168.1.1: icmp_seq=5 ttl=64 time=2.89 ms
64 bytes from 192.168.1.1: icmp_seq=7 ttl=64 time=127 ms
64 bytes from 192.168.1.1: icmp_seq=8 ttl=64 time=85.3 ms
64 bytes from 192.168.1.1: icmp_seq=9 ttl=64 time=89.9 ms
64 bytes from 192.168.1.1: icmp_seq=10 ttl=64 time=179 ms
64 bytes from 192.168.1.1: icmp_seq=11 ttl=64 time=227 ms
64 bytes from 192.168.1.1: icmp_seq=15 ttl=64 time=180 ms
64 bytes from 192.168.1.1: icmp_seq=16 ttl=64 time=102 ms
64 bytes from 192.168.1.1: icmp_seq=21 ttl=64 time=127 ms
64 bytes from 192.168.1.1: icmp_seq=25 ttl=64 time=233 ms
64 bytes from 192.168.1.1: icmp_seq=29 ttl=64 time=117 ms
64 bytes from 192.168.1.1: icmp_seq=31 ttl=64 time=3.69 ms
64 bytes from 192.168.1.1: icmp_seq=32 ttl=64 time=2.66 ms
64 bytes from 192.168.1.1: icmp_seq=33 ttl=64 time=2.79 ms
64 bytes from 192.168.1.1: icmp_seq=36 ttl=64 time=102 ms
64 bytes from 192.168.1.1: icmp_seq=41 ttl=64 time=3.09 ms
64 bytes from 192.168.1.1: icmp_seq=42 ttl=64 time=1.90 ms
64 bytes from 192.168.1.1: icmp_seq=43 ttl=64 time=2.46 ms
64 bytes from 192.168.1.1: icmp_seq=44 ttl=64 time=2.72 ms
64 bytes from 192.168.1.1: icmp_seq=45 ttl=64 time=2.35 ms
64 bytes from 192.168.1.1: icmp_seq=46 ttl=64 time=2.81 ms
64 bytes from 192.168.1.1: icmp_seq=47 ttl=64 time=5.99 ms
64 bytes from 192.168.1.1: icmp_seq=48 ttl=64 time=2.28 ms
64 bytes from 192.168.1.1: icmp_seq=49 ttl=64 time=2.33 ms
64 bytes from 192.168.1.1: icmp_seq=50 ttl=64 time=2.52 ms
64 bytes from 192.168.1.1: icmp_seq=51 ttl=64 time=2.49 ms
64 bytes from 192.168.1.1: icmp_seq=52 ttl=64 time=2.44 ms
64 bytes from 192.168.1.1: icmp_seq=53 ttl=64 time=2.34 ms
64 bytes from 192.168.1.1: icmp_seq=54 ttl=64 time=3.65 ms
64 bytes from 192.168.1.1: icmp_seq=55 ttl=64 time=2.36 ms
64 bytes from 192.168.1.1: icmp_seq=56 ttl=64 time=2.51 ms
64 bytes from 192.168.1.1: icmp_seq=57 ttl=64 time=2.54 ms
64 bytes from 192.168.1.1: icmp_seq=58 ttl=64 time=2.29 ms
64 bytes from 192.168.1.1: icmp_seq=59 ttl=64 time=2.47 ms
64 bytes from 192.168.1.1: icmp_seq=60 ttl=64 time=2.38 ms
64 bytes from 192.168.1.1: icmp_seq=61 ttl=64 time=2.85 ms
64 bytes from 192.168.1.1: icmp_seq=62 ttl=64 time=1.52 ms
64 bytes from 192.168.1.1: icmp_seq=63 ttl=64 time=1.52 ms
64 bytes from 192.168.1.1: icmp_seq=64 ttl=64 time=2.26 ms
64 bytes from 192.168.1.1: icmp_seq=66 ttl=64 time=198 ms
64 bytes from 192.168.1.1: icmp_seq=69 ttl=64 time=1.42 ms
64 bytes from 192.168.1.1: icmp_seq=70 ttl=64 time=162 ms
64 bytes from 192.168.1.1: icmp_seq=71 ttl=64 time=3.80 ms
64 bytes from 192.168.1.1: icmp_seq=72 ttl=64 time=2.70 ms
^C
--- 192.168.1.1 ping statistics ---
72 packets transmitted, 48 received, 33.3333% packet loss, time 71552ms
rtt min/avg/max/mdev = 1.421/43.008/232.642/69.386 ms

**Comment by morrownr** [comment]
Hi @miny1233 

I am aware. There is a serious problem with monitor mode right now:

https://github.com/morrownr/8821au-20210708/issues/70

https://github.com/morrownr/8821cu-20210916/issues/63

It is being worked but no answer so far.
